version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      - CLIENT_STAT_URL=http://localhost:9090
      - STAT_URL_DB=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER_STAT=postgres
      - POSTGRES_PASSWORD_STAT=123
    restart: always

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5466:5432"
    volumes:
      - /var/lib/postgresql/data/
    user: postgres
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  main-service:
    build: ./main
    image: main-server-image
    container_name: main-server-container
    depends_on:
      main-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - CLIENT_MAIN_URL=http://localhost:8080
      - MAIN_URL_DB=jdbc:postgresql://main-db:5433/main
      - POSTGRES_USER_MAIN=postgres
      - POSTGRES_PASSWORD_MAIN=123
    restart: always

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "5467:5433"
    volumes:
      - /var/lib/postgresql/data/
    user: postgres
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always