version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - CLIENT_STAT_URL=http://localhost:9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5466:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
