DROP TABLE IF EXISTS stat;

CREATE TABLE IF NOT EXISTS stat
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app     VARCHAR                     NOT NULL,
    uri     VARCHAR                     NOT NULL,
    ip      VARCHAR                     NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
)